### ISSUE TITLE
Quick Alchemy makes Medium sized bombs and elixirs for Tiny player character 

### ISSUE THREAD

**Issue by captnobody61** [thejoester/pf2e-alchemist-remaster-ducttape#2]
Pretty much the title. Playing a sprite and when I quick alchemy the items are medium sized and make me encumbered.

**Comment by thejoester** [comment]
> Pretty much the title. Playing a sprite and when I quick alchemy the items are medium sized and make me encumbered.

Looking into this… rules wise I’m not sure that it works that way RAW. Nowhere do I find that Quick Alchemy makes smaller items or that consumables are size dependent. 

Will keep looking but in the meantime I’ll work on making it an optional setting.

**Comment by captnobody61** [comment]
Thank you. Sprites are Tiny pcs so anything they make should also be tiny
or they wouldn't be able to use them.

**Comment by captnobody61** [comment]
Here's the specific rule entries.

https://2e.aonprd.com/Rules.aspx?ID=2164

https://2e.aonprd.com/Rules.aspx?ID=2165

**Comment by thejoester** [comment]
Personally, I agree with you and that’s how I would run it (have a sprite player in one of my games), however the consensus online including the PF2e discord is that those rules apply to permanent items not consumables, as consumables do not (in the rules) have a size. Otherwise everyone would just load up on tiny consumables that would be negligible for them.

So for now I’ll still make it optional but not the default setting.



Sent from my iPhone

On Nov 24, 2024, at 1:03 PM, captnobody61 ***@***.***> wrote:

﻿

Here's the specific rule entries.

https://2e.aonprd.com/Rules.aspx?ID=2164

https://2e.aonprd.com/Rules.aspx?ID=2165

**Comment by captnobody61** [comment]
Gotcha. So it's just foundry programing forcing all equipment to have a
size despite the rules?

**Comment by thejoester** [comment]
This should be fixed with [v2.1.0](https://github.com/thejoester/pf2e-alchemist-remaster-ducttape/releases/tag/2.1.0)

**Comment by captnobody61** [comment]
Thanks for the update and all the work on the module. Appreciate it!
